In [1]:
import numpy as np

# Q1.Create a null vector (all zeros) of size 10 and set it in the variable called “Z”.

In [2]:
Z = np.zeros(10, dtype=int)
Z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Q2. Create a 1D array of numbers from 0 to 9 and set it in the variable called “arr”. 

In [3]:
arr = np.arange(0, 10,1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Q3. Create a 3x3x3 array with random values and set it in the variable called “arr”.

In [4]:
arr = np.random.randint(10, size=(3, 3, 3))
arr

array([[[3, 0, 3],
        [9, 6, 1],
        [8, 5, 4]],

       [[7, 1, 0],
        [4, 0, 2],
        [3, 5, 0]],

       [[1, 9, 1],
        [6, 5, 7],
        [1, 0, 3]]])

# Q4. Create a 10x10 array with random values called “arr4”. Find its minimum and maximum values and set them in the variables called “min_val” and “max_val” respectively.

In [5]:
arr4 = np.random.randint(10, size=(10,10))
arr4

array([[9, 5, 5, 7, 0, 4, 3, 8, 7, 4],
       [2, 7, 1, 0, 1, 7, 5, 1, 6, 5],
       [1, 9, 7, 9, 2, 6, 2, 7, 4, 7],
       [9, 2, 8, 9, 8, 4, 0, 2, 2, 5],
       [8, 9, 8, 9, 8, 9, 2, 7, 7, 4],
       [3, 9, 6, 7, 0, 2, 2, 2, 8, 7],
       [9, 5, 6, 6, 1, 2, 4, 0, 2, 2],
       [1, 7, 6, 6, 6, 9, 6, 8, 1, 8],
       [3, 9, 3, 8, 4, 2, 6, 1, 8, 4],
       [4, 6, 4, 7, 5, 7, 1, 1, 3, 2]])

In [6]:
min_val = arr4.min()
# min_val

max_val= arr4.max()
max_val



9

# Q5. First create a 1D array with numbers from 1 to 9 and then convert it into a 3x3 grid. Store the final answer in the variable called “grid”.

In [7]:
grid = np.arange(1,10,1).reshape((3,3))


# Q6. Replace the maximum value in the given vector, “arr6”, with -1. 

In [8]:
# Input
arr6 = np.arange(10)

arr6[arr6.argmax()] = -1

# Q7. Reverse the rows of the given 2D array, “arr7”. 

In [9]:
# Input
arr7 = np.arange(9).reshape(3,3)

arr7 = arr7[::-1]

# Q8. Subtract the mean of each row of the given 2D array, “arr8”, from the values in the array. Set the updated array in “transformed_arr8”.

In [10]:
# To get the mean along the row axis, you can use the numpy.mean method, mean(axis=1, keepdims=True).

# Input
arr8 = np.random.rand(3, 10)
 
transformed_arr8 = arr8 - arr8.mean(axis=1, keepdims=True)
transformed_arr8

array([[ 0.22121772,  0.32475997, -0.14655073, -0.10013349, -0.23992323,
         0.05961586,  0.10294367,  0.01868064, -0.34312851,  0.1025181 ],
       [ 0.28514511,  0.37419941, -0.44159426, -0.09122749,  0.02853372,
        -0.08691162,  0.03909047,  0.46569414, -0.2199316 , -0.35299788],
       [-0.09167035,  0.0605338 , -0.32117997,  0.2043517 , -0.34437937,
         0.39374972, -0.15497976, -0.28169493,  0.01034867,  0.52492049]])